config/routes.rb
require 'geo_ip'

Travis::Application.routes.draw do
  root to: 'home#show'
  match 'company_packages', to: 'home#sponsoring_plans'
  match 'ads',              to: 'home#sponsoring_sizes'
  match 'imprint',          to: 'home#imprint'
  match 'ringtones',        to: 'home#ringtones'
  match 'sponsors',         to: 'home#sponsors'

  match 'packages/:package', as: :new_package, to: 'orders#new'
  match 'subscriptions/:package', as: :new_subscription, to: 'orders#new', subscription: true
  match 'geo_ip.json', to: GeoIP.new

  resources :orders, except: :new do
    get 'confirm', on: :member
  end

  resource :profile do
    get 'ringtones', on: :member
    match 'ringtones/:permalink.mp3', on: :member, action: :ringtone, as: :ringtone
  end

  match '/donations.json', to: 'orders#index', as: :donors

  devise_for :users, controllers: { omniauth_callbacks: 'sessions' }

  as :user do
    get 'users/sign_out', to: 'devise/sessions#destroy', as: :destroy_session
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!

  def update
    current_user.update_attributes!(params[:user])
    render :json => current_user.as_json.merge(email: current_user.email)
  end

  def ringtone
    if track = Track.find(permalink: params[:permalink])
      redirect_to track.download_url
    else
      render text: 'File Not Found', status: 404
    end
  end
end

app/views/profiles/ringtones.html.haml
- content_for :head do
  <script type="text/javascript" src="/javascripts/soundcloud.player.api.js"></script>

%h2 Ringtones &amp; sounds

%p
  If you wonder what the heck these ringtones are about, we've written up the
  %a{ href: '/ringtones' } full story
  for you.

%p
  %object{height: 81, width: '100%', id: 'soundcloud', classid: 'clsid:D27CDB6E-AE6D-11cf-96B8-444553540000'}
    %param{name: 'movie', value: "https://player.soundcloud.com/player.swf?url=#{Playlist.first.tracks.first.permalink_url}&enable_api=true&object_id=soundcloud"}
    %param{name: 'allowscriptaccess', value: 'always'}
    %embed{allowscriptaccess: 'always', height: 81, width: '100%', src: "https://player.soundcloud.com/player.swf?url=#{Playlist.first.tracks.first.permalink_url}&enable_api=true&object_id=soundcloud", type: 'application/x-shockwave-flash', name: 'soundcloud'}

- Playlist.each do |playlist|
  %table.playlist
    %colgroup
      %col.col-track
      %col.col-duration
      %col.col-download
    %thead
      %tr
        %th
          %h3= "#{playlist.title} (#{playlist.tracks.size})"
        %th{colspan: 2}
          .pagination
            = render partial: 'home/pagination'
    %tbody
      - playlist.tracks.each do |track|
        %tr
          %td.track
            = link_to track.title, track.permalink_url, {}, :'data-src' => track.uri
          %td
            = "#{(track.duration / 100).round(1) / 10} sec" # hrmm
          %td
            = link_to 'Download', ringtone_profile_path(permalink: track.permalink)

app/views/profiles/show.html.haml
%div#profile
  %h2{:'data-object' => 'user'}
    %img{ src: current_user.gravatar_url(:size => 50) }
    = current_user_editable(:span, :name)

  #contact
    %h3 Contact

    %dl{:'data-object' => 'user'}
      %dt Email
      = current_user_editable(:dd, :email)
      %dt Twitter
      = current_user_editable(:dd, :twitter_handle)
      %dt Github
      = current_user_editable(:dd, :github_handle)
      %dt Homepage
      = current_user_editable(:dd, :homepage)

  - unless current_user.subscriptions.empty?
    #subscriptions
      %h3 Subscriptions
      %table
        = render current_user.subscriptions

  - unless current_user.packages.empty?
    #packages
      %h3 Packages
      %table
        = render current_user.packages

  #ringtones
    %h3 Ringtones
    :markdown
      Feel free to download the [ringtones](/profile/ringtones) and other recordings.