config/routes.rb
require 'geo_ip'

Travis::Application.routes.draw do
  root to: 'home#show'
  match 'company_packages', to: 'home#sponsoring_plans'
  match 'ads',              to: 'home#sponsoring_sizes'
  match 'imprint',          to: 'home#imprint'
  match 'ringtones',        to: 'home#ringtones'
  match 'sponsors',         to: 'home#sponsors'

  match 'packages/:package', as: :new_package, to: 'orders#new'
  match 'subscriptions/:package', as: :new_subscription, to: 'orders#new', subscription: true
  match 'geo_ip.json', to: GeoIP.new

  resources :orders, except: :new do
    get 'confirm', on: :member
  end

  resource :profile do
    get 'ringtones', on: :member
    match 'ringtones/:permalink.mp3', on: :member, action: :ringtone, as: :ringtone
  end

  match '/donations.json', to: 'orders#index', as: :donors

  devise_for :users, controllers: { omniauth_callbacks: 'sessions' }

  as :user do
    get 'users/sign_out', to: 'devise/sessions#destroy', as: :destroy_session
  end
end

app/views/layouts/_flashes.html.haml
- if request.host != 'love.travis-ci.org'
  %div{class: "flash alert"}
    %p This is just a demo page, donations will <u>not</u> reach us!

- flash.each do |name, msg|
  %div{class: "flash #{name}"}
    %p= msg

app/views/layouts/_footer.html.haml
%footer
  %div
    %ul
      %li <a href="http://travis-ci.org">Travis CI</a>
      %li <a href="http://about.travis-ci.org/blog">Blog</a>
      %li <a href="http://github.com/travis-ci">Github</a>
      %li <a href="/imprint">Imprint (Germany)</a>

    %ul
      %li Twitter: <a href="http://twitter.com/travisci">@travisci</a>
      %li E-Mail: <a href="mailto:contact@travis-ci.org">contact@travis-ci.org</a>
      %li IRC: <a href="irc://irc.freenode.net#travis">irc.freenode.net#travis</a>
      %li Group: <a href="http://groups.google.com/group/travis-ci">travis-ci</a>



-# %footer#suggestions
-#   %form{action: '#', onsubmit: 'SuggestWidget.submitSuggestion(); return false;'}
-#     %input{type: 'text', placeholder: 'You guys should ...'}
-#     %input{type: 'submit', value: 'Send feedback'}

app/views/layouts/_gauges.html.haml
- if Rails.env.production?
  :javascript
    var _gauges = _gauges || [];
    (function() {
      var t   = document.createElement('script');
      t.type  = 'text/javascript';
      t.async = true;
      t.id    = 'gauges-tracker';
      t.setAttribute('data-site-id', "#{Rails.application.config.settings.gauges}");
      t.src = '//secure.gaug.es/track.js';
      var s = document.getElementsByTagName('script')[0];
      s.parentNode.insertBefore(t, s);
    })();

app/views/layouts/_header.html.haml
%header#top
  %h1
    %a{ href: '/' } Travis CI
  %h2 Continuous Integration for the Open Source Community
  %ul
    - if signed_in?
      %li= "Welcome, #{current_user.name}"
      %li= '&rarr;'.html_safe
      %li= link_to 'Your Profile', profile_path
      %li= link_to 'Sign out', destroy_session_path
    - else
      %li= link_to 'Sign in', new_user_session_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Travis needs your help
    = stylesheet_link_tag 'application'
    /[if lt IE 9]
      = stylesheet_link_tag 'ie'
    = javascript_include_tag 'https://js.stripe.com/v1', 'application'
    = csrf_meta_tags
    = tag :meta, name: 'stripe-key', content: STRIPE_PUBLIC_KEY
    = tag :meta, name: 'viewport', content: 'width=1010,maximum-scale=1.4'
    = tag :meta, name: 'pusher-key', content: Rails.application.config.settings.pusher[:key] if Rails.application.config.settings.pusher
    = yield :head

  %body{id: page_id}
    %header#closed
      %h1 Thank you so much!
      %p
        The Travis Love Campaign has been closed. We'll follow up with a blog post
        soon, but for now we'd like to say a <strong>HUGE THANK YOU</strong> to everyone who
        participated and made this such a big success!
    #github
      %a{ href: 'https://github.com/travis-ci/travis-crowd', title: 'Fork me on GitHub'} Fork me on GitHub
    = render partial: 'layouts/flashes'
    #wrap
      #page
        = render partial: 'layouts/header'
        - if params[:controller] == 'home'
          = yield
        - else
          %section.paper
            = yield
        = render partial: 'layouts/footer'
        = render partial: 'layouts/gauges'

app/views/layouts/email.html.haml
!!! 5
%html
  %head
    %meta{:content => 'text/html; charset=UTF-8', :'http-equiv' => 'Content-Type'}
    = stylesheet_link_tag 'email'

  %body
    .header
      %img{src: 'http://love.travis-ci.org/images/travis-ci.png'}
      %ul.contact
        %li
          E-Mail:
          %a{href: 'mailto:contact@travis-ci.org'} contact@travis-ci.org
        %li
          Twitter:
          %a{href: 'http://twitter.com/travisci'} @travisci

    .content
      = yield

  %footer
    %div
      %img{src: 'http://love.travis-ci.org/images/footer.png'}

      %ul.address
        %li Travis CI GmbH
        %li Prinzessinnenstrasse 20
        %li 10969 Berlin
        %li Germany

      %ul
        %li <a href="http://travis-ci.org">http://travis-ci.org</a>
        %li <a href="mailto:contact@travis-ci.org">contact@travis-ci.org</a>
        %li <a href="http://twitter.com/travisci">@travisci</a>
        %li <a href="irc://irc.freenode.net#travis">irc.freenode.net#travis</a>

app/views/layouts/email.text.erb
<%= yield %>

Travis CI: http://travis-ci.org
Blog:      http://about.travis-ci.org/blog
Help:      http://about.travis-ci.org
Github:    http://github.com/travis-ci

Twitter: http://twitter.com/travisci
E-Mail:  contact@travis-ci.org
IRC:     irc.freenode.net#travis
Group:   http://groups.google.com/group/travis-ci